hyundaiPlastic/Controllers/BlobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Azure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using System.IO;

namespace hyundaiPlastic.Controllers
{
    public class BlobsController : Controller
    {
        // GET: Blobs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateBlobContainer()
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("hyundaiplastic_AzureStorageConnectionString"));
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("hyundaiplastic");
            ViewBag.Success = container.CreateIfNotExists();
            ViewBag.BlobContainerName = container.Name;
            return View();
        }

        public EmptyResult UploadBlob()
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("hyundaiplastic_AzureStorageConnectionString"));
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("hyundaiplastic");
            CloudBlockBlob blob = container.GetBlockBlobReference("blobexample");
            
            using (var fileStream = System.IO.File.OpenRead(@"C:\Project\IMG_8332.jpg"))
            {
                blob.UploadFromStream(fileStream);
            }
            return new EmptyResult();
        }
        public ActionResult ListBlobs()
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("hyundaiplastic_AzureStorageConnectionString"));
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("hyundaiplastic");

            List<string> blobs = new List<string>();
            foreach(IListBlobItem item in container.ListBlobs(useFlatBlobListing:true))
            {
                if (item.GetType() == typeof(CloudBlockBlob))
                {
                    CloudBlockBlob blob = (CloudBlockBlob)item;
                    
                    blobs.Add(blob.Uri.ToString());
                }
                else if (item.GetType() == typeof(CloudPageBlob))
                {
                    CloudPageBlob blob = (CloudPageBlob)item;
                    blobs.Add(blob.Name);
                }
                else if (item.GetType() == typeof(CloudBlobDirectory))
                {
                    CloudBlobDirectory dir = (CloudBlobDirectory)item;
                    blobs.Add(dir.Uri.ToString());
                }
            }
            return View(blobs);
        }
        public EmptyResult DownloadBlob()
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("hyundaiplastic_AzureStorageConnectionString"));
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("hyundaiplastic");
            CloudBlockBlob blob = container.GetBlockBlobReference("IMG_8316.jpg");
            using (var fileStream = System.IO.File.OpenWrite(@"C:\Project\downloadedImage.jpg"))
            {
                blob.DownloadToStream(fileStream);
            }
            return new EmptyResult();
        }
    }
}

hyundaiPlastic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 현대플라스틱</title>

    <link rel="apple-touch-icon" sizes="180x180" href="~/favicons/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicons/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicons/favicon-16x16.png" />
    <link rel="manifest" href="~/favicons/manifest.json" />
    <link rel="mask-icon" href="~/favicons/safari-pinned-tab.svg" color="#5bbad5" />
    <meta name="theme-color" content="#ffffff" />
    <meta name="description" content="현대플라스틱은 성주군에 위치한 전국 최대 규모의 플라스틱 제품 생산 공장입니다." />

    <link rel="canonical" href="http://www.hyundaiplastic.co.kr">
    <meta property="fb:app_id" content="139345863285782">
    <meta property="og:type" content="website">
    <meta property="og:title" content="현대플라스틱">
    <meta property="og:description" content="현대플라스틱은 성주군에 위치한 전국 최대 규모의 플라스틱 제품 생산 공장입니다.">
    <meta property="og:image" content="https://hyundaiplastic.blob.core.windows.net/hyundaiplastic/HDPlasticLogo.jpg">
    <meta property="og:url" content="http://www.hyundaiplastic.co.kr">


    @*<link rel="icon" href="~/favicon.ico" sizes="32x32" />
    <link rel="icon" href="~/favicon.ico" sizes="192x192" />*@
    <link rel="apple-touch-icon" href="~/favicons/apple-touch-icon-120x120.png"/>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
         <!--       <li>@Html.ActionLink("회사", "Index", "Home")</li> -->
                    <li>@Html.ActionLink("제품", "About", "Home")</li>
                    <li>@Html.ActionLink("연락처", "Contact", "Home")</li>
          <!--      <li>@Html.ActionLink("Create blob container", "CreateBlobContainer", "Blobs")</li>
                    <li>@Html.ActionLink("Upload blob", "UploadBlob", "Blobs")</li>
                    <li>@Html.ActionLink("List blobs", "ListBlobs", "Blobs")</li>
                    <li>@Html.ActionLink("Download blob", "DownloadBlob", "Blobs")</li> -->
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Copyright &copy; @DateTime.Now.Year - 현대플라스틱</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>